# Generated by Django 5.1.1 on 2024-12-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_be_app', 'add_difficulty_to_questiontaxonomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.CharField(default='CO0000', max_length=100, unique=True),
        ),
    ]
