# Generated by Django 5.1.1 on 2024-12-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_be_app', '0001_course_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='created_by',
            new_name='owner',
        ),
    ]
