# Generated by Django 5.1.2 on 2024-12-07 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_be_app', 'course_migration'),
        ('mcq_be_app', 'new_migration'),
    ]

    operations = [
    ]
