# Generated by Django 5.1.3 on 2025-03-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_be_app', '0005_test_testquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='title',
            field=models.CharField(default='Untitled Test', max_length=255),
        ),
    ]
