# Generated by Django 5.1.3 on 2025-04-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_be_app', '0009_testdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
    ]
